--Explore all objects in the database
select * from information_schema.tables
where table_catalog='DatawarehouseAnalytics';

--Explore all columns in the Database
select * from information_schema.columns
where table_name='dim_customers';

-------------------------------------------------------------------------------------------------
/* Dimension Exploration */
-------------------------------------------------------------------------------------------------
--Explore all countries our customers come from 
select distinct country from gold.dim_customers;
select distinct category, subcategory, product_name from gold.dim_products
order by 1, 2, 3;

--Find the dates of the first and the last order
select * from gold.fact_sales;
select min(order_date) AS first_order_date, max(order_date) AS last_order_date
from gold.fact_sales;

--Find how many years of sales are available
SELECT 
    MIN(order_date) AS first_order_date, 
    MAX(order_date) AS last_order_date, 
    DATE_PART('year', AGE(MAX(order_date), MIN(order_date))) AS years_difference
FROM gold.fact_sales;

--Find the youngest and the oldest customer
select 
min(birthdate) as youngest,
DATE_PART('year', AGE(MAX(birthdate), MIN(birthdate))) AS years_difference,
max(birthdate) as oldest
from gold.dim_customers;


-------------------------------------------------------------------------------------------------
/* Measure Exploration */
-------------------------------------------------------------------------------------------------
--Find the total sales
select * from gold.fact_sales;
select sum(sales_amount) as total_sales
from gold.fact_sales;

--Find how many items are sold
select SUM(quantity) as total_sales from gold.fact_sales;

--Find the average selling price
select round(avg(price),2) as average_sales from gold.fact_sales;

--Find the total number of orders
select count(distinct order_number) as total_orders from gold.fact_sales;

--Find the total number of products
select * from gold.dim_products;
select count(product_id) as total_products from gold.dim_products;

--Find the total number of customers
select * from gold.dim_customers;
select count(customer_id) from gold.dim_customers;

--Find the total number of customers that has placed an order;
select * from gold.fact_sales;

select count(customer_key) from gold.dim_customers;
select count(customer_key) from gold.dim_customers
where customer_key IN (select customer_key from gold.fact_sales);

--Generate a report that shows all key metrics of the business
select 'Total Sales' as measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales
union all
select 'Total Quantity' as measure_name, SUM(quantity) AS measure_value FROM gold.fact_sales
union all
select 'Average Price' as measure_name, round(AVG(price),2) AS measure_value FROM gold.fact_sales
union all
select 'Total Nr. Orders' as measure_value, count(distinct order_number) from gold.fact_sales
union all
select 'Total Nr. Products' as measure_value, count(distinct product_name) from gold.dim_products
union all
select 'Total Nr. Customers' as measure_value, count(distinct customer_key) from gold.dim_customers;

-------------------------------------------------------------------------------------------------
/* Magnitude Exploration */
-------------------------------------------------------------------------------------------------

--Find the total number of customers by countries
select * from gold.dim_customers;
select 
country,
count(customer_key) AS total_customers
from gold.dim_customers
group by country
order by total_customers DESC;

--Find total customers by genders
select gender, count(customer_key) AS total_customers
from gold.dim_customers
group by gender
order by total_customers DESC;

--Find the total products by category
select * from gold.dim_products;
select 
category,
count(product_id) as total_products
from gold.dim_products
group by category
order by total_products DESC;

--What is the average costs in each category
select * from gold.fact_sales;
select 
	category,
	round(avg(cost),2) as avg_cost
from gold.dim_products
group by category
order by avg_cost DESC;

--What is the total revenue generated for each category?
select * from gold.fact_sales;
select * from gold.dim_products;

select 
	category,
	sum(fact_s.sales_amount) as total_revenue
from gold.fact_sales fact_s
left join gold.dim_products dim_p 
on fact_s.product_key=dim_p.product_key
group by category
order by total_revenue;

--What is the total revenue generated by each customer
select * from gold.fact_sales;
select * from gold.dim_customers;

select 
	c.first_name||' '||c.last_name as customer_name,
	sum(f.sales_amount) as total_revenue
from gold.fact_sales f
left join gold.dim_customers c
on f.customer_key=c.customer_key
group by c.first_name, c.last_name 
order by total_revenue DESC;

--What is the distribution of sold items across countries?
select * from gold.fact_sales;
select * from gold.dim_customers;

select 
	c.country as country,
	SUM(f.quantity) as total_qty_sold
from gold.fact_sales f
left join gold.dim_customers c
on f.customer_key=c.customer_key
group by c.country
order by total_qty_sold DESC;

-------------------------------------------------------------------------------------------------
/* Ranking Exploration */
-------------------------------------------------------------------------------------------------
--Which 5 products generate the highest revenue? 
select * from gold.dim_products;
select * from gold.fact_sales;

--Approach 1
select
p.product_name,
sum(f.sales_amount) total_revenue
from gold.fact_sales f
left join gold.dim_products p
on p.product_key=f.product_key
group by p.product_name
order by total_revenue desc
limit 5;

--Approach 2
select * from
(
select
p.product_name,
row_number() over (order by sum(f.sales_amount) desc) as rank_products
from gold.fact_sales f
left join gold.dim_products p
on p.product_key=f.product_key
group by p.product_name
)t where rank_products<=5;


--What are the 5 worst-performing products in terms of sales?
select
p.product_name,
sum(f.sales_amount) total_revenue
from gold.fact_sales f
left join gold.dim_products p
on p.product_key=f.product_key
group by p.product_name
order by total_revenue asc
limit 5;

select * from
(
select 
	p.product_name,
	row_number() over (order by sum(f.sales_amount) asc) as product_rank
from gold.fact_sales f
left join gold.dim_products p
on p.product_key=f.product_key
group by p.product_name)t
where product_rank<=5;

--Find the top-10 customers who have generated the highest revenue and 3 customers with the fewest orders placed

select * from
(
select 
c.first_name||' '||c.last_name as customer_name,
sum(f.sales_amount) as total_revenue,
row_number() over (order by sum(f.sales_amount) desc) as customer_rank
from gold.fact_sales f 
left join gold.dim_customers c
on f.customer_key=c.customer_key
group by c.first_name, c.last_name)t
where customer_rank<=10;



select * from
(
select 
c.first_name||' '||c.last_name as customer_name,
sum(f.sales_amount) as total_revenue,
row_number() over (order by sum(f.sales_amount) asc) as customer_rank
from gold.fact_sales f 
left join gold.dim_customers c
on f.customer_key=c.customer_key
group by c.first_name, c.last_name)t
where customer_rank<=3;